meta_product_name: "Tin Tức Mỗi Ngày"
meta_title: "Read News - Tin Tức Mỗi Ngày"
meta_keywords: "Vietnam News Daily,Economy,Online,Internet,Magazine,Gateway,FPT,Portal,Tin nhanh,cập nhật,báo điện tử,việt báo,tin việt,VietNews,mua bán,rao vặt,tư vấn,việc làm,Hà Nội,Sài Gòn,tin tức,Huế,Đà Nẵng,VDC,Netnam,Saigonnet,Sggp,VET,Nhân dân,Lao động,Kinh tế,Kinh doanh,Tin nhanh,cap nhat,bao dien tu,Vietbao,TinViet,Mua Ban,Rao Vat,Tu Van,Viec Lam,Hanoi,Ha Noi,Saigon,Sai gon,Tin tuc,Tintuc,Hue,Da Nang,Danang,Nhandan,Nhan dan,Laodong,Lao dong,Kinhte,Kinh te,Kinhdoanh,Kinh doanh"
meta_description: "Tin Tức Tổng Hợp cập nhật liên tục từng giờ, tin hot, tin hot ngày hôm nay "
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@khanhnvhcm"   # required for Twitter Cards
